version: '3.9'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    container_name: vuejs_client
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      - NODE_ENV=production
    command: npm run build

  nginx:
    build:
      context: ./.nginx
      dockerfile: Dockerfile
    image: nginx
    volumes:
      - ./.nginx/sites-available/prod.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist:/home/alfa/client/dist
    ports:
      - "80:80"
    command: ["/wait-for", "client", "--", "nginx", "-g", "daemon off;"]

networks:
  default:
    external:
      name: prod_network