#!/bin/sh

set -e

host="$1"
port="$2"
shift 2
cmd="$@"

until curl --output /dev/null --silent --head --fail "http://$host:$port"; do
  echo "Waiting for host '$host' and port '$port' to be available..."
  sleep 1
done

exec $cmd